{
 "title": "云原生应用网络（ANC）",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "云原生应用网络指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "入方向带宽",
   "type": "timeseries",
   "description": "跨区域流入本区域的带宽。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_network_incoming_bits_rate{epId=\"$EPS\"}",
     "legendFormat": "anc资源名：{{name}}"
    }
   ]
  },
  {
   "title": "出方向带宽",
   "type": "timeseries",
   "description": "当前云原生应用网络的出方向带宽。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_network_outgoing_bits_rate{epId=\"$EPS\"}",
     "legendFormat": "anc资源名：{{name}}"
    }
   ]
  },
  {
   "title": "入方向流量",
   "type": "timeseries",
   "description": "跨区域流入本区域的流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_network_incoming_packets_rate{epId=\"$EPS\"}",
     "legendFormat": "anc资源名：{{name}}"
    }
   ]
  },
  {
   "title": "出方向流量",
   "type": "timeseries",
   "description": "跨区域流出本区域的流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_network_outgoing_packets_rate{epId=\"$EPS\"}",
     "legendFormat": "anc资源名：{{name}}"
    }
   ]
  },
  { "title": "云原生应用网络服务指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "服务入方向流量",
   "type": "timeseries",
   "description": "引流到当前服务的流量。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_service_inbound_traffic{epId=~\"$EPS\", anc_service_id=~\".+\", anc_serviceregion_id!~\".+\"}",
     "legendFormat": "服务名称：{{name}}"
    }
   ]
  },
  {
   "title": "服务出方向流量",
   "type": "timeseries",
   "description": "从当前服务流出的流量。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_service_outbound_traffic{epId=~\"$EPS\", anc_service_id=~\".+\", anc_serviceregion_id!~\".+\"}",
     "legendFormat": "服务名称：{{name}}"
    }
   ]
  },
  { "title": "云原生应用网络成员组指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "全部成员数",
   "type": "timeseries",
   "description": "本成员组的全部成员数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_total_server_count{epId=~\"$EPS\"}",
     "legendFormat": "成员组名：{{name}}"
    }
   ]
  },
  {
   "title": "正常成员数",
   "type": "timeseries",
   "description": "本成员组的正常成员数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_healthy_server_count{epId=~\"$EPS\"}",
     "legendFormat": "成员组名：{{name}}"
    }
   ]
  },
  {
   "title": "异常成员数",
   "type": "timeseries",
   "description": "本成员组的异常成员数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "huaweicloud_sys_anc_unhealthy_server_count{epId=~\"$EPS\"}",
     "legendFormat": "成员组名：{{name}}"
    }
   ]
  }
 ]
}