{
 "title": "API网关专享版（APIC）",
 "description": "【API网关专享版监控指标说明】https://support.huaweicloud.com/usermanual-apig/apig_03_0032.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "专享版API网关-实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "api接口被调用次数【企业项目：$EPS】",
   "type": "graph",
   "description": "统计测量api接口被调用的次数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_requests{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}（api接口被调用次数）"
    }
   ]
  },
  {
   "title": "4xx 异常次数【企业项目：$EPS】",
   "type": "graph",
   "description": "统计测量api接口返回4xx错误的次数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_error_4xx{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}（4xx 异常次数）"
    }
   ]
  },
  {
   "title": "5xx 异常次数【企业项目：$EPS】",
   "type": "graph",
   "description": "统计测量api接口返回5xx错误的次数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_error_5xx{epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}（5xx 异常次数）"
    }
   ]
  },
  {
   "title": "平均延迟毫秒数【企业项目：$EPS】",
   "type": "graph",
   "description": "统计测量api接口平均响应延时时间。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_avg_latency{appName!~\".+\",epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}（平均延迟毫秒数）"
    }
   ]
  },
  {
   "title": "最大延迟毫秒数【企业项目：$EPS】",
   "type": "graph",
   "description": "统计测量api接口最大响应延时时间。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_max_latency{appName!~\".+\",epId=~\"$EPS\"}",
     "legendFormat": "{{instanceName}}（平均延迟毫秒数）"
    }
   ]
  },
  { "title": "专项版API网关-API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "接口调用次数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口调用次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_req_count{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "2xx调用次数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口调用2xx的次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_req_count_2xx{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "4xx调用次数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口调用4xx的次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_req_count_4xx{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "5xx调用次数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口调用5xx的次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_req_count_5xx{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "异常次数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口总的错误次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "次/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_req_count_error{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "平均延迟毫秒数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口平均响应延时时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_avg_latency{appName=~\".+\",epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "最大延迟毫秒数【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口最大响应延时时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_max_latency{appName=~\".+\",epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "流入流量【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口请求流量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "byte/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_input_throughput{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  {
   "title": "流出流量【企业项目：$EPS】",
   "type": "graph",
   "description": "该指标用于统计测量api接口返回流量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "byte/min" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_output_throughput{epId=~\"$EPS\"}",
     "legendFormat": "实例名：{{instanceName}}；App应用名：{{appName}}；API组名：{{groupName}}"
    }
   ]
  },
  { "title": "专享版API网关-节点", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "网关节点系统负载【企业项目：$EPS】",
   "type": "graph",
   "description": "统计当前数据面网关节点负载详情，1表示低水位，2表示中水位，3表示高水位。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_node_system_load{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}；节点类型：{{nodeType}}；节点IP：{{nodeIP}}"
    }
   ]
  },
  {
   "title": "网关节点cpu使用率【企业项目：$EPS】",
   "type": "graph",
   "description": "统计当前数据面网关节点cpu使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_node_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}；节点类型：{{nodeType}}；节点IP：{{nodeIP}}"
    }
   ]
  },
  {
   "title": "网关节点内存使用率【企业项目：$EPS】",
   "type": "graph",
   "description": "统计当前数据面网关节点内存使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_apic_node_memory_usage{epId=~\"$EPS\"}",
     "legendFormat": "实例名称：{{instanceName}}；节点类型：{{nodeType}}；节点IP：{{nodeIP}}"
    }
   ]
  }
 ]
}