{
 "title": "弹性伸缩",
 "description": "【华为云弹性伸缩监控指标说明】https://support.huaweicloud.com/usermanual-as/as_06_0105.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "弹性伸缩资源概览【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_as_cpu_util{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_mem_usedPercent{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_instance_num{epId=\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_disk_read_bytes_rate{epId=\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_disk_write_bytes_rate{epId=\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_load_average1{epId=\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_load_average5{epId=\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_as_load_average15{epId=\"$EPS\"}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "CPU使用率-弹性伸缩：该指标用于统计所有云服务器的CPU使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_cpu_util{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（CPU使用率）"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "内存使用率-弹性伸缩：该指标用于统计所有云服务器的内存使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_mem_usedPercent{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（内存使用率）"
    }
   ]
  },
  {
   "title": "带内网络流入速率",
   "type": "graph",
   "description": "带内网络流入速率-弹性伸缩：该指标用于统计所有云服务器的网络流入速率的均值",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "byte/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_network_incoming_bytes_rate_inband{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（带内网络流入速率）"
    }
   ]
  },
  {
   "title": "带内网络流出速率",
   "type": "graph",
   "description": "带内网络流出速率-弹性伸缩：该指标用于统计所有云服务器的网络流出速率的均值",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "byte/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_network_outgoing_bytes_rate_inband{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（带内网络流出速率）"
    }
   ]
  },
  {
   "title": "实例数",
   "type": "graph",
   "description": "实例数-弹性伸缩：该指标用于统计可用的云服务器数量",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_instance_num{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（实例数）"
    }
   ]
  },
  {
   "title": "磁盘读速率",
   "type": "graph",
   "description": "磁盘读速率-弹性伸缩：该指标用于统计每秒从测量对象读出数据量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "byte/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_disk_read_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘读速率）"
    }
   ]
  },
  {
   "title": "磁盘写速率",
   "type": "graph",
   "description": "磁盘写速率-弹性伸缩：该指标用于统计每秒写到测量对象的数据量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "byte/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_disk_write_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘写速率）"
    }
   ]
  },
  {
   "title": "磁盘读操作速率",
   "type": "graph",
   "description": "磁盘读操作速率-弹性伸缩：该指标用于统计每秒从测量对象读取数据的请求次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_disk_read_requests_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘读操作速率）"
    }
   ]
  },
  {
   "title": "磁盘写操作速率",
   "type": "graph",
   "description": "磁盘写操作速率-弹性伸缩：该指标用于统计每秒从测量对象写数据的请求次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_disk_write_requests_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘写操作速率）"
    }
   ]
  },
  {
   "title": "（Agent）CPU使用率",
   "type": "graph",
   "description": "（Agent）CPU使用率-弹性伸缩：该指标用于统计测量对象中所有云服务器的CPU使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）CPU使用率"
    }
   ]
  },
  {
   "title": "（Agent）内存使用率",
   "type": "graph",
   "description": "（Agent）内存使用率-弹性伸缩：该指标用于统计测量对象中所有云服务器的内存使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_mem_usedPercent{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）内存使用率"
    }
   ]
  },
  {
   "title": "（Agent）1分钟平均负载",
   "type": "graph",
   "description": "（Agent）1分钟平均负载-弹性伸缩：该指标用于统计测量对象中所有云服务器过去1分钟的CPU平均负载",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_load_average1{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）1分钟平均负载"
    }
   ]
  },
  {
   "title": "（Agent）5分钟平均负载",
   "type": "graph",
   "description": "（Agent）5分钟平均负载-弹性伸缩：该指标用于统计测量对象中所有云服务器过去5分钟的CPU平均负载",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_load_average5{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）5分钟平均负载"
    }
   ]
  },
  {
   "title": "（Agent）15分钟平均负载",
   "type": "graph",
   "description": "（Agent）15分钟平均负载-弹性伸缩：该指标用于统计测量对象中所有云服务器过去15分钟的CPU平均负载",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_load_average15{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）15分钟平均负载"
    }
   ]
  },
  {
   "title": "（Agent）GPU使用率",
   "type": "graph",
   "description": "（Agent）GPU使用率-弹性伸缩：该指标用于统计测量对象中所有云服务器的GPU使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_gpu_usage_gpu{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）GPU使用率"
    }
   ]
  },
  {
   "title": "（Agent）显存使用率",
   "type": "graph",
   "description": "（Agent）显存使用率-弹性伸缩：该指标用于统计测量对象中所有云服务器的显存使用率的均值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_as_gpu_usage_mem{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} -（Agent）显存使用率"
    }
   ]
  }
 ]
}