{
 "title": "云连接",
 "description": "【云连接服务监控指标说明】https://support.huaweicloud.com/usermanual-cc/cc_03_0802.html",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "网络带宽使用率",
   "type": "graph",
   "description": "网络带宽使用率-云连接：云连接域间带宽数据使用率。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_bandwidth_usage{connectionEpId=~\"$EPS\"}"
    }
   ]
  },
  {
   "title": "网络流入带宽",
   "type": "graph",
   "description": "网络流入带宽-云连接：云连接域间入站数据的比特率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_bits_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流出带宽",
   "type": "graph",
   "description": "网络流出带宽-云连接：云连接域间出站数据的比特率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_bits_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流入流量",
   "type": "graph",
   "description": "网络流入流量-云连接：云连接域间入站数据的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_bytes{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流出流量",
   "type": "graph",
   "description": "网络流出流量-云连接：云连接域间出站数据的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_bytes{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流入包速率",
   "type": "graph",
   "description": "网络流入包速率-云连接：云连接域间入站数据包速率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "包/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_packets_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流出包速率",
   "type": "graph",
   "description": "网络流出包速率-云连接：云连接域间出站数据包速率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "包/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_packets_rate{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流入包量",
   "type": "graph",
   "description": "网络流入包量-云连接：云连接域间入站数据包数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "包" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_incoming_packets{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  },
  {
   "title": "网络流出包量",
   "type": "graph",
   "description": "网络流出包量-云连接：云连接域间出站数据包数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "包" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_cc_network_outgoing_packets{connectionEpId=~\"$EPS\"}",
     "legendFormat": "连接名称：{{connectionName}}；带宽包名：{{packageName}}"
    }
   ]
  }
 ]
}