{
 "title": "表格存储服务（CloudTable）",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterName", "label": "集群名称", "query": { "query": "label_values(clusterName)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率（节点）",
   "type": "timeseries",
   "description": "统计测量对象的CPU使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessCPU{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "内存使用率（节点）",
   "type": "timeseries",
   "description": "统计测量对象的内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdProcessMem{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "已用存储空间比率（节点）",
   "type": "timeseries",
   "description": "统计测量对象所在集群的已用存储空间大小占总配额的比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdForUsedStorageRate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "已用存储空间比率（节点）",
   "type": "timeseries",
   "description": "统计测量对象所在集群的已用存储空间大小占总配额的比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_cmdForUsedStorageRate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "磁盘吞吐读速率（节点）",
   "type": "timeseries",
   "description": "磁盘读取吞吐速率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_read_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  },
  {
   "title": "磁盘吞吐写速率（节点）",
   "type": "timeseries",
   "description": "磁盘写入吞吐速率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_cloudtable_disk_throughput_write_rate{clusterName=~\"$ClusterName\"}",
     "legendFormat": "集群名称：{{clusterName}}；节点名称：{{instance_name}}"
    }
   ]
  }
 ]
}