{
 "title": "云搜索服务(CSS/ES)",
 "description": "【华为云CSS支持的监控指标】https://support.huaweicloud.com/usermanual-css/css_01_0042.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "Cluster",
    "label": "CSS集群名称",
    "query": {
     "query": "label_values(huaweicloud_sys_es_cpu_usage{epId=~\"$EPS\"},name)"
    }
   },
   {
    "name": "privateIp",
    "label": "主机IP",
    "query": {
     "query": "label_values(huaweicloud_sys_es_cpu_usage{epId=~\"$EPS\",name=~\"$Cluster\"},privateIp)"
    }
   },
   {
    "name": "instanceName",
    "label": "实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_es_cpu_usage{epId=~\"$EPS\",name=~\"$Cluster\"},instanceName)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_sys_es_cpu_usage{name=~\"$Cluster\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（企业项目）企业项目：$EPS，当前选中集群：$Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_es_status{epId=~'$EPS'}",
     "legendFormat": "健康状态"
    },
    {
     "expr": "avg(huaweicloud_sys_es_avg_cpu_usage{epId=~'$EPS'}) by (name)",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_es_avg_mem_used_percent{epId=~'$EPS'}) by (name)",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_es_disk_util{epId=~'$EPS'}) by (name)",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_es_max_jvm_heap_usage{epId=~'$EPS'}) by (name)",
     "legendFormat": "最大JVM堆使用率"
    },
    {
     "expr": "avg(huaweicloud_sys_es_indices_count{epId=~'$EPS'}) by (name)",
     "legendFormat": "索引数量"
    },
    {
     "expr": "avg(huaweicloud_sys_es_avg_load_average{epId=~'$EPS'}) by (name)",
     "legendFormat": "平均负载"
    }
   ]
  },
  {
   "title": "集群健康状态",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_status{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群健康状态"
    }
   ]
  },
  {
   "title": "集群最大CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_max_cpu_usage{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大CPU使用率"
    },
    {
     "expr": "huaweicloud_agt_ecs_SlAsHdata_disk_usedPercent{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘使用率（/data）"
    },
    {
     "expr": "huaweicloud_agt_ecs_SlAsHdata_disk_usedPercent{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘使用率（/data1）"
    },
    {
     "expr": "huaweicloud_agt_ecs_SlAsHdata1_disk_usedPercent{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘使用率（/data2）"
    },
    {
     "expr": "huaweicloud_agt_ecs_SlAsHdata2_disk_usedPercent{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘使用率（/data3）"
    },
    {
     "expr": "huaweicloud_agt_ecs_SlAsHdata3_disk_usedPercent{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘使用率（/data4）"
    }
   ]
  },
  {
   "title": "集群内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_mem_used_percent{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_内存使用率"
    }
   ]
  },
  {
   "title": "集群磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_disk_util{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_磁盘使用率"
    }
   ]
  },
  {
   "title": "节点数量（Totle | master｜data｜client）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_nodes_count{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_节点数量"
    },
    {
     "expr": "huaweicloud_sys_es_data_nodes_count{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_数据节点数量"
    },
    {
     "expr": "huaweicloud_sys_es_master_nodes_count{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_Master节点数量"
    },
    {
     "expr": "huaweicloud_sys_es_ingest_nodes_count{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_Client节点数量"
    }
   ]
  },
  {
   "title": "分片数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_total_shards_count{epId=~\"$EPS\",name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_分片数量"
    }
   ]
  },
  {
   "title": "索引数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_indices_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_索引数量"
    }
   ]
  },
  {
   "title": "集群文档数量&删除文档数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "文档数量（+）/删除文档数量（-）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_docs_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群文档数量"
    },
    {
     "expr": "0 - huaweicloud_sys_es_docs_deleted_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群删除文档数量"
    }
   ]
  },
  {
   "title": "平均（查询/索引）速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_SearchRate{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均查询速率"
    },
    {
     "expr": "huaweicloud_sys_es_IndexingRate{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均索引速率"
    }
   ]
  },
  {
   "title": "平均（查询/索引）时延",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_SearchLatency{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均查询时延"
    },
    {
     "expr": "huaweicloud_sys_es_IndexingLatency{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均索引时延"
    }
   ]
  },
  {
   "title": "集群Search队列（平均/最大/总计）数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_thread_pool_search_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Search队列平均数量"
    },
    {
     "expr": "huaweicloud_sys_es_max_thread_pool_search_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Search队列最大数量"
    },
    {
     "expr": "huaweicloud_sys_es_sum_thread_pool_search_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Search队列总计数量"
    }
   ]
  },
  {
   "title": "集群Write队列（平均/最大/总计）数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_thread_pool_write_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Write队列平均数量"
    },
    {
     "expr": "huaweicloud_sys_es_max_thread_pool_write_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Write队列最大数量"
    },
    {
     "expr": "huaweicloud_sys_es_sum_thread_pool_write_queue{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_集群Write队列总计数量"
    }
   ]
  },
  {
   "title": "平均/最大/总计JVM YOUNG GC次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_jvm_young_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均JVM YOUNG GC次数"
    },
    {
     "expr": "huaweicloud_sys_es_max_jvm_young_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大JVM YOUNG GC次数"
    },
    {
     "expr": "huaweicloud_sys_es_sum_jvm_young_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_总计JVM YOUNG GC次数"
    }
   ]
  },
  {
   "title": "平均/最大/总计JVM YOUNG GC耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_jvm_young_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均JVM YOUNG GC耗时"
    },
    {
     "expr": "huaweicloud_sys_es_max_jvm_young_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大JVM YOUNG GC耗时"
    },
    {
     "expr": "huaweicloud_sys_es_sum_jvm_young_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_总计JVM YOUNG GC耗时"
    }
   ]
  },
  {
   "title": "平均/最大/总计JVM OLD GC次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_jvm_old_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均JVM OLD GC次数"
    },
    {
     "expr": "huaweicloud_sys_es_max_jvm_old_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大JVM OLD GC次数"
    },
    {
     "expr": "huaweicloud_sys_es_sum_jvm_old_gc_count{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_总计JVM OLD GC次数"
    }
   ]
  },
  {
   "title": "平均/最大/总计JVM OLD GC耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_avg_jvm_old_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_平均JVM OLD GC耗时"
    },
    {
     "expr": "huaweicloud_sys_es_max_jvm_old_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大JVM OLD GC耗时"
    },
    {
     "expr": "huaweicloud_sys_es_sum_jvm_old_gc_time{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_总计JVM OLD GC耗时"
    }
   ]
  },
  {
   "title": "集群JVM使用率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_es_max_jvm_heap_usage{epId=~'$EPS',name=~\"$Cluster\"}",
     "legendFormat": "{{name}}_最大JVM堆使用率"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$Cluster】【$privateIp】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(huaweicloud_sys_es_cpu_usage{epId=~'$EPS',name=~\"$Cluster\",privateIp=~'$privateIp'}) by (privateIp,instanceName)",
     "legendFormat": "{{privateIp}}_{{instanceName}}_CPU使用率"
    }
   ]
  },
  {
   "title": "Search队列任务数&Search队列拒绝任务数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_thread_pool_search_queue{name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_Search队列任务数"
    },
    {
     "expr": "0 - huaweicloud_sys_es_thread_pool_search_rejected{name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_Search队列拒绝任务数"
    }
   ]
  },
  {
   "title": "Write队列任务数&Write队列拒绝任务数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_thread_pool_write_queue{name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_Write队列任务数"
    },
    {
     "expr": "0 - huaweicloud_sys_es_thread_pool_write_rejected{name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_Write队列拒绝任务数"
    }
   ]
  },
  {
   "title": "JVM(YOUNG/OLD)GC次数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_jvm_young_gc_count{epId=~\"$EPS\",name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_JVM YOUNG GC次数"
    },
    {
     "expr": "huaweicloud_sys_es_jvm_old_gc_count{epId=~\"$EPS\",name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_JVM OLD GC次数"
    }
   ]
  },
  {
   "title": "JVM(YOUNG/OLD)GC耗时",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_es_jvm_young_gc_time{epId=~\"$EPS\",name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_JVM YOUNG GC耗时"
    },
    {
     "expr": "huaweicloud_sys_es_jvm_old_gc_time{epId=~\"$EPS\",name=~\"$Cluster\",privateIp=~\"$privateIp\"}",
     "legendFormat": "{{privateIp}}_{{instanceName}}_JVM OLD GC耗时"
    }
   ]
  }
 ]
}