{
 "title": "云专线（DCAAS）",
 "description": "【华为云DCASS支持的监控指标】https://support.huaweicloud.com/usermanual-dc/dc_04_0802.html",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "专线IP",
    "query": {
     "query": "label_values(huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\"},device_id)"
    }
   },
   {
    "name": "hostname",
    "label": "专线名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\", device_id=~\"$hostIP\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "资源总览-华为云专线 企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "云专线资源总览表",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bits_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dcaas_network_outgoing_bits_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\"}) by (name) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_outgoing_bytes{epId=~\"$EPS\"}) by (name) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_incoming_packets_rate{epId=~\"$EPS\"}) by (name) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_network_outgoing_packets_rate{epId=~\"$EPS\"}) by (name) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_latency{epId=~\"$EPS\"}) by (name) - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(huaweicloud_sys_dcaas_packet_loss_rate{epId=~\"$EPS\"}) by (name) -0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "资源明细：【$EPS】【$hostIP】【$hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "网络(流入/流出)带宽",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bits_rate{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流入带宽）"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_bits_rate{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流出带宽）"
    }
   ]
  },
  {
   "title": "网络(流入/流出)流量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_bytes{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流入流量）"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_bytes{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流出流量）"
    }
   ]
  },
  {
   "title": "网络(流入/流出)包速率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_packets_rate{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流入包速率）"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_packets_rate{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流出包速率）"
    }
   ]
  },
  {
   "title": "网络(流入/流出)包量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dcaas_network_incoming_packets{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流入包量）"
    },
    {
     "expr": "0 - huaweicloud_sys_dcaas_network_outgoing_packets{epId=~\"$EPS\",device_id=~\"$hostIP\",name=~\"$hostname\"}",
     "legendFormat": "专线IP：{{device_id}}，专线名称：({{name}}（网络流出包量）"
    }
   ]
  }
 ]
}