{
 "title": "数据湖探索-DLI",
 "description": "【华为云数据湖探索支持的监控指标】https://support.huaweicloud.com/usermanual-dli/dli_01_0445.html",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "DLI队列指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DLI队列指标概览【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_cpu_usage{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_dli_queue_mem_usage{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_dli_queue_disk_usage{epId=~\"$EPS\"}"
    }
   ]
  },
  {
   "title": "队列CPU使用率",
   "type": "graph",
   "description": "队列CPU使用率：展示用户队列的CPU使用率。",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_cpu_usage{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "队列内存使用率",
   "type": "graph",
   "description": "队列内存使用率：展示用户队列的内存使用率。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_mem_usage{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "队列磁盘使用率",
   "type": "graph",
   "description": "队列磁盘使用率：展示用户队列的磁盘使用率。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_disk_usage{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "提交中作业数",
   "type": "graph",
   "description": "展示用户队列中状态为提交中的作业数。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_job_launching_num{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "运行中作业数",
   "type": "graph",
   "description": "展示用户队列中状态为运行中的作业数。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_job_running_num{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "已完成作业数",
   "type": "graph",
   "description": "展示用户队列中状态为已完成的作业数。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_job_succeed_num{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  {
   "title": "已失败作业数",
   "type": "graph",
   "description": "展示用户队列中状态为已失败的作业数。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_queue_job_failed_num{epId=~\"$EPS\"}",
     "legendFormat": "队列名称：{{name}}"
    }
   ]
  },
  { "title": "DLI Flink作业指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "DLI Flink指标概览",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_flink_cpu_usage"
    },
    {
     "expr": "huaweicloud_sys_dli_flink_mem_usage"
    }
   ]
  },
  {
   "title": "Flink作业CPU使用率",
   "type": "graph",
   "description": "展示用户Flink作业的CPU使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_flink_cpu_usage",
     "legendFormat": "作业名称：{{name}}；作业类型：{{job_type}}"
    }
   ]
  },
  {
   "title": "Flink作业内存使用率",
   "type": "graph",
   "description": "展示用户Flink作业的内存使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_flink_mem_usage",
     "legendFormat": "作业名称：{{name}}；作业类型：{{job_type}}"
    }
   ]
  },
  {
   "title": "Flink作业字节输入速率",
   "type": "graph",
   "description": "展示用户Flink作业每秒输入的字节数。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_flink_read_bytes_per_second\r\n\r",
     "legendFormat": "作业名称：{{name}}；作业类型：{{job_type}}"
    }
   ]
  },
  {
   "title": "Flink作业字节输出速率",
   "type": "graph",
   "description": "展示用户Flink作业每秒输出的字节数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dli_flink_write_bytes_per_second\r\n\r",
     "legendFormat": "作业名称：{{name}}；作业类型：{{job_type}}"
    }
   ]
  }
 ]
}