{
 "title": "分布式消息服务(Kafka)",
 "description": "【文档数据库服务监控指标说明】https://support.huaweicloud.com/usermanual-dds/dds_03_0026.html",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "instancename",
    "label": "Kafka实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_current_partitions{epId=\"$EPS\"},instanceName)"
    }
   },
   {
    "name": "kafka_broker",
    "label": "broker节点",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_broker_data_size{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_broker)"
    }
   },
   {
    "name": "kafka_group",
    "label": "消费组",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_messages_consumed{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_groups)"
    }
   },
   {
    "name": "kafka_topic",
    "label": "topic",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_topic_bytes_in_rate{epId=~\"$EPS\", instanceName=~\"$instancename\"},kafka_topics)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "实例资源总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS",
   "targets": [
    {}
   ]
  },
  {
   "title": "实例级资源总览表【企业项目：$EPS，实例名称：$instancename】",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_current_partitions{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "分区数"
    },
    {
     "expr": "huaweicloud_sys_dms_current_topics{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "主题数"
    },
    {
     "expr": "huaweicloud_sys_dms_group_msgs{epId=~\"$EPS\",kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "消息堆积数"
    }
   ]
  },
  {
   "title": "Broker节点监控 （节点名称：【$kafka_broker】）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "统计Kafka节点虚拟机的CPU使用率",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_cpu_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "该指标为Kafka节点虚拟机层面采集的内存使用率",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_memory_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "Kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "description": "该指标为从Kafka节点虚拟机层面采集的磁盘容量使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_disk_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "Kafka实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "broker连接数",
   "type": "graph",
   "description": "统计Kafka节点当前所有TCP连接数量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_connections{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "生产流量",
   "type": "graph",
   "description": "该指标用于统计每秒生产的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消费流量",
   "type": "graph",
   "description": "该指标用于统计每秒消费的字节数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "生产请求平均处理时长",
   "type": "graph",
   "description": "统计Broker节点处理生产请求平均时长",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_produce_mean{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "消费请求平均处理时长",
   "type": "graph",
   "description": "统计Broker节点处理消费请求平均时长",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_fetch_mean{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_broker=~\"$kafka_broker\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "Kafka进程JVM堆内存使用率",
   "type": "graph",
   "description": "该指标从Kafka节点Kafka进程JVM中采集的堆内存使用率",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_heap_usage{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，Broker名称：{{kafka_broker}}"
    }
   ]
  },
  {
   "title": "Topic监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "消息生产/消费流量",
   "type": "graph",
   "description": "该指标用于统计每秒生产/消费的字节数",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "binBps", "label": "消费（-）/生产（+）" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_bytes_in_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"} - 0",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}-生产流量"
    },
    {
     "expr": "0 - huaweicloud_sys_dms_topic_bytes_out_rate{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}-消费流量"
    }
   ]
  },
  {
   "title": "队列数据容量",
   "type": "graph",
   "description": "该指标用于统计队列当前的消息数据大小",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_data_size{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "队列消息总数",
   "type": "graph",
   "description": "该指标用于统计队列当前的消息总数",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}"
    }
   ]
  },
  {
   "title": "队列关联分区数",
   "type": "table",
   "description": "用于标识各个topic下的分区数量",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(huaweicloud_sys_dms_partition_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"}) by (instanceName, kafka_topics)"
    }
   ]
  },
  {
   "title": "分区消息数（只显示消息数大于10000的分区）",
   "type": "graph",
   "description": "该指标用于统计队列当前的消息总数",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_partition_messages{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_topics=~\"$kafka_topic\"} > 10000",
     "legendFormat": "实例名称：{{instanceName}}，Topic名称：{{kafka_topics}}，分区编号：{{kafka_partitions}}"
    }
   ]
  },
  {
   "title": "消费组监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "消息堆积数（消费组可消费消息数）",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_remained{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  },
  {
   "title": "消费组已消费消息数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_consumed{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  },
  {
   "title": "消费组消费速率",
   "type": "graph",
   "description": "统计消费组每分钟的消费数。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumer_messages_consumed_per_min{epId=~\"$EPS\", kafka_instance_id=~\".+\", instanceName=~\"$instancename\", kafka_groups=~\"$kafka_group\"}",
     "legendFormat": "实例名称：{{instanceName}}，消费组名称：{{kafka_groups}}"
    }
   ]
  }
 ]
}