{
 "title": "分布式消息服务RabbitMQ",
 "description": "【华为云DMS（RabbitMQ）支持的监控指标】https://support.huaweicloud.com/intl/zh-cn/usermanual-rabbitmq/rabbitmq-ug-180413002.html",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "EPS",
    "label": "企业项目",
    "query": {
     "query": "query_result(huaweicloud_epinfo)"
    }
   },
   {
    "name": "instancename",
    "label": "实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_dms_publish{epId=\"$EPS\"},instanceName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "分布式消息服务（RabbitMQ）实例指标监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "分布式消息服务（RabbitMQ）实例指标概览（企业项目：$EPS）",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_publish{epId=~\"$EPS\",instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_consumers{epId=~\"$EPS\",instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_channels{epId=~\"$EPS\",instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_connections{epId=~\"$EPS\",instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_queues{epId=~\"$EPS\",instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实例消息生产速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "个/秒" } },
   "yaxes": [
    { "format": "个/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_publish{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例消费者数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_consumers{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例通道数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_channels{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_connections{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例队列数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_queues{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例可消费消息数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_ready{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  {
   "title": "实例未确认消息数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_messages_unacknowledged{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}"
    }
   ]
  },
  { "title": "分布式消息服务（RabbitMQ）节点指标监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "分布式消息服务（RabbitMQ）节点状态总览",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_memory_high_watermark{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_disk_insufficient{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_alive{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_cpu_usage{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "节点内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_memory_usage{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "节点磁盘容量使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_rabbitmq_disk_usage{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "节点erlang进程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_proc_used{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{rabbitmq_node}}"
    }
   ]
  },
  {
   "title": "节点socket连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_socket_used{epId=~\"$EPS\", instanceName=~\"$instancename\"}",
     "legendFormat": "实例名称：{{instanceName}}，节点名称：{{rabbitmq_node}}"
    }
   ]
  }
 ]
}