{
 "title": "云解析服务 DNS",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "记录集NOERROR解析次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dns_recordset_noerror_count",
     "legendFormat": "{{dns_recordset_id}}"
    }
   ]
  },
  {
   "title": "解析成功请求量统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dns_zone_noerror_count{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "解析不存在请求量统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dns_zone_nxdomain_count{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "解析失败请求量统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dns_zone_servfail_count{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}