{
 "title": "数据复制服务",
 "description": "【华为云数据复制服务监控指标说明】https://support.huaweicloud.com/realtimemig-drs/drs_03_0106.html",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "数据复制服务概览【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_cpu_util{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_mem_util{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_network_incoming_bytes_rate{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_network_outgoing_bytes_rate{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_disk_util{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_disk_read_bytes_rate{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_drs_disk_write_bytes_rate{epId=~\"$EPS\"}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "CPU使用率-数据复制服务：该指标用于统计测量对象的CPU使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_cpu_util{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（CPU使用率）"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "内存使用率-数据复制服务：该指标用于统计测量对象的内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_mem_util{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（内存使用率）"
    }
   ]
  },
  {
   "title": "网络输入吞吐量",
   "type": "graph",
   "description": "网络输入吞吐量-数据复制服务：该指标用于统计平均每秒从测量对象的所有网络适配器输入的流量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_network_incoming_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（网络输入吞吐量）"
    }
   ]
  },
  {
   "title": "网络输出吞吐量",
   "type": "graph",
   "description": "网络输出吞吐量-数据复制服务：该指标用于统计平均每秒从测量对象的所有网络适配器输出的流量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_network_outgoing_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（网络输出吞吐量）"
    }
   ]
  },
  {
   "title": "磁盘利用率",
   "type": "graph",
   "description": "磁盘利用率-数据复制服务：该指标用于统计测量对象的磁盘利用率",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_disk_util{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘利用率）"
    }
   ]
  },
  {
   "title": "磁盘读吞吐量",
   "type": "graph",
   "description": "磁盘读吞吐量-数据复制服务：该指标用于统计每秒从磁盘读取的字节数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_disk_read_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘读吞吐量）"
    }
   ]
  },
  {
   "title": "磁盘写吞吐量",
   "type": "graph",
   "description": "磁盘写吞吐量-数据复制服务：该指标用于统计每秒从磁盘写入的字节数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_disk_write_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（磁盘写吞吐量）"
    }
   ]
  },
  {
   "title": "读源库吞吐量",
   "type": "graph",
   "description": "读源库吞吐量-数据复制服务：该指标用于统计每秒从源库读取表数据或者WAL的字节数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_extract_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（读源库吞吐量）"
    }
   ]
  },
  {
   "title": "读源库频率",
   "type": "graph",
   "description": "读源库频率-数据复制服务：该指标用于统计每秒从源库读取表数据或者WAL的行数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "row/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_extract_rows_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（读源库频率）"
    }
   ]
  },
  {
   "title": "源库WAL抽取延迟",
   "type": "graph",
   "description": "源库WAL抽取延迟-数据复制服务：该指标用于统计当前从源库抽取WAL的延迟",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_extract_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（源库WAL抽取延迟）"
    }
   ]
  },
  {
   "title": "写目标库吞吐量",
   "type": "graph",
   "description": "写目标库吞吐量-数据复制服务：该指标用于统计每秒向目标库写入数据的字节数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_bytes_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（写目标库吞吐量）"
    }
   ]
  },
  {
   "title": "写目标库频率",
   "type": "graph",
   "description": "写目标库频率-数据复制服务：该指标用于统计每秒向目标库写入数据的行数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "row/s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_rows_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（写目标库频率）"
    }
   ]
  },
  {
   "title": "DML TPS",
   "type": "graph",
   "description": "DML TPS-数据复制服务：该指标用于统计每秒向目标库写入的DML事务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_transactions_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（DML TPS）"
    }
   ]
  },
  {
   "title": "DDL TPS",
   "type": "graph",
   "description": "DDL TPS-数据复制服务：该指标用于统计每秒向目标库写入的DDL事务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_ddls_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（DDL TPS）"
    }
   ]
  },
  {
   "title": "数据同步延迟",
   "type": "graph",
   "description": "数据同步延迟-数据复制服务：该指标用于统计当前数据同步的延迟",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_latency{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（数据同步延迟）"
    }
   ]
  },
  {
   "title": "事务平均执行时间",
   "type": "graph",
   "description": "事务平均执行时间-数据复制服务：该指标用于统计当前一个事务在目标库的平均执行时间(一个事务的RT=执行时间+提交时间)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_average_execute_time{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（事务平均执行时间）"
    }
   ]
  },
  {
   "title": "事务平均提交时间",
   "type": "graph",
   "description": "事务平均提交时间-数据复制服务：该指标用于统计当前一个事务在目标库的平均提交时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_drs_apply_average_commit_time{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}（事务平均提交时间）"
    }
   ]
  }
 ]
}