{
 "title": "事件网格（EG）",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "事件源 （企业项目：$EPS）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "事件源事件数",
   "type": "timeseries",
   "description": "该指标为单位时间处理该类型事件源事件数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_event_num{epId=~\"$EPS\"}",
     "legendFormat": "事件源名称：{{name}}"
    }
   ]
  },
  { "title": "事件通道（企业项目：$EPS）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "通道接入事件数量",
   "type": "timeseries",
   "description": "该指标为单位时间通道接入事件数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_pub_num{epId=~\"$EPS\"}",
     "legendFormat": "事件通道名称：{{name}}"
    }
   ]
  },
  {
   "title": "通道接入事件失败数量",
   "type": "timeseries",
   "description": "该指标为单位时间通道接入失败数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_pub_failed_num{epId=~\"$EPS\"}",
     "legendFormat": "事件通道名称：{{name}}"
    }
   ]
  },
  {
   "title": "通道接入事件成功数量",
   "type": "timeseries",
   "description": "该指标为单位时间通道接入事件成功数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_pub_success_num{epId=~\"$EPS\"}",
     "legendFormat": "事件通道名称：{{name}}"
    }
   ]
  },
  { "title": "事件订阅（企业项目：$EPS）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "投递事件数量",
   "type": "timeseries",
   "description": "该指标为单位时间订阅投递事件数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_sub_num{epId=~\"$EPS\", subscription_name!~\".+\"}",
     "legendFormat": "事件订阅名称：{{name}}"
    }
   ]
  },
  {
   "title": "投递事件成功数量",
   "type": "timeseries",
   "description": "该指标为单位时间订阅投递事件成功数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_sub_success_num{epId=~\"$EPS\", subscription_name!~\".+\"}",
     "legendFormat": "事件订阅名称：{{name}}"
    }
   ]
  },
  {
   "title": "投递事件失败数量",
   "type": "timeseries",
   "description": "该指标为单位时间订阅投递事件失败数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_sub_failed_num{epId=~\"$EPS\", subscription_name!~\".+\"}",
     "legendFormat": "事件订阅名称：{{name}}"
    }
   ]
  },
  {
   "title": "投递事件重试数量",
   "type": "timeseries",
   "description": "该指标为单位时间订阅投递事件重试数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "huaweicloud_sys_eg_sub_retry_num{epId=~\"$EPS\", subscription_name!~\".+\"}",
     "legendFormat": "事件订阅名称：{{name}}"
    }
   ]
  }
 ]
}