{
 "title": "云硬盘",
 "description": "【华为云云硬盘监控指标说明】https://support.huaweicloud.com/usermanual-evs/evs_01_0044.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "云硬盘【企业项目: $EPS】",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_requests_rate{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_requests_rate{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_await{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_await{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_evs_disk_device_queue_length{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_evs_disk_device_io_svctm{epId=~\"$EPS\"}"
    }
   ]
  },
  {
   "title": "磁盘读IOPS",
   "type": "graph",
   "description": "云硬盘-磁盘读IOPS：该指标用于统计每秒从测量对象读取数据的请求次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "请求/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_requests_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘读IOPS"
    }
   ]
  },
  {
   "title": "磁盘写IOPS",
   "type": "graph",
   "description": "云硬盘-磁盘写IOPS：该指标用于统计每秒写到测量对象的请求次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "请求/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_requests_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘写IOPS"
    }
   ]
  },
  {
   "title": "磁盘读操作耗时",
   "type": "graph",
   "description": "云硬盘-磁盘读操作耗时：该指标用于统计指定时间段内，平均每个读IO的操作时长",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms/op" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_await{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘读操作耗时"
    }
   ]
  },
  {
   "title": "磁盘写操作耗时",
   "type": "graph",
   "description": "云硬盘-磁盘写操作耗时：该指标用于统计指定时间段内，平均每个写IO的操作时长",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms/op" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_await{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘写操作耗时"
    }
   ]
  },
  {
   "title": "平均队列长度",
   "type": "graph",
   "description": "云硬盘-平均队列长度：该指标用于统计指定时间段内，平均等待完成的读取或写入操作请求的数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_queue_length{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘平均队列长度"
    }
   ]
  },
  {
   "title": "平均IO服务时长",
   "type": "graph",
   "description": "云硬盘-平均IO服务时长：该指标用于统计指定时间段内，平均每个读或写IO的操作时长",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms/op" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_io_svctm{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘平均IO服务时长"
    }
   ]
  },
  {
   "title": "磁盘读带宽",
   "type": "graph",
   "description": "云硬盘-磁盘读带宽：该指标用于统计每秒从测量对象读出数据量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_bytes_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘读带宽"
    }
   ]
  },
  {
   "title": "磁盘写带宽",
   "type": "graph",
   "description": "云硬盘-磁盘写带宽：该指标用于统计每秒写到测量对象的数据量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_bytes_rate{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘写带宽"
    }
   ]
  },
  {
   "title": "磁盘平均读操作大小",
   "type": "graph",
   "description": "云硬盘-平均读操作大小：该指标用于统计指定时间段内，平均每个读IO操作传输的字节数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "KB/op" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_read_bytes_per_operation{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘平均读操作大小"
    }
   ]
  },
  {
   "title": "磁盘平均写操作大小",
   "type": "graph",
   "description": "云硬盘-平均写操作大小：该指标用于统计指定时间段内，平均每个写IO操作传输的字节数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "KB/op" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_write_bytes_per_operation{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘平均写操作大小小"
    }
   ]
  },
  {
   "title": "磁盘读写使用率",
   "type": "graph",
   "description": "云硬盘-磁盘读写使用率：该指标用于统计指定时间段内，提交读取或写入操作的占比",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_io_util{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-磁盘读写使用率"
    }
   ]
  },
  {
   "title": "IOPS达到上限(次数)",
   "type": "graph",
   "description": "云硬盘-IOPS达到上限(次数)：卷IOPS达到上限次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "次" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_io_iops_qos_num{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-IOPS达到上限(次数)"
    }
   ]
  },
  {
   "title": "带宽达到上限(次数)",
   "type": "graph",
   "description": "云硬盘-带宽达到上限(次数)：卷带宽达到上限次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "次" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_evs_disk_device_io_iobw_qos_num{epId=~\"$EPS\"} - 0",
     "legendFormat": "{{name}}({{device}})-带宽达到上限(次数)"
    }
   ]
  }
 ]
}