{
 "title": "函数工作流",
 "description": "【函数工作流服务监控指标说明】https://support.huaweicloud.com/usermanual-functiongraph/functiongraph_01_0213.html",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "函数工作流-函数资源总览【企业项目：$EPS】",
   "type": "table",
   "description": "函数工作流-函数资源总览：以5min为周期监控函数指标",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_count{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_functiongraph_concurrency{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_functiongraph_duration{epId=~\"$EPS\"}"
    },
    {
     "expr": "huaweicloud_sys_functiongraph_failRate{epId=~\"$EPS\"}"
    }
   ]
  },
  {
   "title": "调用次数",
   "type": "graph",
   "description": "调用次数：以5min为周期，统计函数调用次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "次/5分钟" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_count{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "并发数",
   "type": "graph",
   "description": "并发数：以5min为周期，统计函数同时调用处理的最大并发请求个数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_concurrency{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "平均运行时间",
   "type": "graph",
   "description": "平均运行时间：以5min为周期，统计函数在该周期内德平均运行时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_duration{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "description": "错误率：以5min为周期，统计该周期内函数调用错误次数在总调用次数中的占比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_failRate{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "最大运行时间",
   "type": "graph",
   "description": "最大运行时间：以5min为周期，统计该周期内函数调用的最大运行时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_maxDuration{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "最小运行时间",
   "type": "graph",
   "description": "最小运行时间：以5min为周期，统计该周期内函数调用的最小运行时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_minDuration{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "错误次数",
   "type": "graph",
   "description": "错误次数：以5min为周期，统计该周期内函数调用的错误次数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "次" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_failcount{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "被拒绝次数",
   "type": "graph",
   "description": "错误次数：以5min为周期，统计该周期内函数调用的被拒绝次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "次" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_rejectcount{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "资源使用量",
   "type": "graph",
   "description": "资源使用量：该指标用于统计函数执行资源使用量，函数执行内存使用 * 函数执行时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_functionCost{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  },
  {
   "title": "函数执行内存使用",
   "type": "graph",
   "description": "函数执行内存使用：该指标用于统计函数执行内存使用量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_functiongraph_memoryUsed{epId=~\"$EPS\"}",
     "legendFormat": "函数名：{{function_name}}；程序包名：{{package}}"
    }
   ]
  }
 ]
}