{
 "title": "GAUSSDBV5",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_gaussdbv5_rds001_cpu_util, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "云数据库 GaussDBV5资源概览",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds001_cpu_util{name=~\"$InstanceName\"}"
    },
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds002_mem_util{name=~\"$InstanceName\"}"
    },
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds005_instance_disk_used_size{name=~\"$InstanceName\"}"
    },
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds006_instance_disk_total_size{name=~\"$InstanceName\"}"
    },
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds007_instance_disk_usage{name=~\"$InstanceName\"}"
    }
   ]
  },
  {
   "title": "实例数据磁盘已使用大小",
   "type": "graph",
   "description": "实例数据磁盘已使用大小-云数据库 GaussDB：该指标用于统计测量对象的实例数据磁盘已使用大小，该值为实时值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds005_instance_disk_used_size{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例数据磁盘已使用大小）"
    }
   ]
  },
  {
   "title": "实例数据磁盘已使用百分比",
   "type": "graph",
   "description": "实例数据磁盘已使用百分比-云数据库 GaussDB：该指标用于统计测量对象的实例数据磁盘使用率，该值为实时值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds007_instance_disk_usage{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例数据磁盘已使用百分比）"
    }
   ]
  },
  {
   "title": "实例buffer 命中率",
   "type": "graph",
   "description": "实例buffer 命中率-云数据库 GaussDB：该指标用于统计数据库buffer命中率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds035_buffer_hit_ratio{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例buffer 命中率）"
    }
   ]
  },
  {
   "title": "实例死锁次数",
   "type": "graph",
   "description": "实例死锁次数-云数据库 GaussDB：该指标用于统计数据库发生事务死锁的次数，取该时间段的增量值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "次" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds036_deadlocks{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例死锁次数）"
    }
   ]
  },
  {
   "title": "实例80% SQL的响应时间",
   "type": "graph",
   "description": "实例80% SQL的响应时间-云数据库 GaussDB：该指标用于统计数据库80% SQL的响应时间，该值为实时值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "微秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds048_P80{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例80% SQL的响应时间）"
    }
   ]
  },
  {
   "title": "实例95% SQL的响应时间",
   "type": "graph",
   "description": "实例95% SQL的响应时间-云数据库 GaussDB：该指标用于统计数据库95% SQL的响应时间，该值为实时值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "微秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds049_P95{name=~\"$InstanceName\"}",
     "legendFormat": "{{name}}（实例95% SQL的响应时间）"
    }
   ]
  },
  {
   "title": "节点CPU使用率",
   "type": "graph",
   "description": "节点CPU使用率-云数据库 GaussDB：该指标用于统计测量对象的CPU使用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds001_cpu_util{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点CPU使用率）"
    }
   ]
  },
  {
   "title": "节点内存使用率",
   "type": "graph",
   "description": "节点内存使用率-云数据库 GaussDB：该指标用于统计测量对象的内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds002_mem_util{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点内存使用率）"
    }
   ]
  },
  {
   "title": "节点数据写入量",
   "type": "graph",
   "description": "节点数据写入量-云数据库 GaussDB：该指标用于统计测量对象对应VM的网络发送字节数，取时间段的平均值",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds003_bytes_in{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据写入量）"
    }
   ]
  },
  {
   "title": "节点数据传出量",
   "type": "graph",
   "description": "节点数据传出量-云数据库 GaussDB：该指标用于统计测量对象对应VM的网络接受字节数，取时间段的平均值",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds004_bytes_out{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据传出量）"
    }
   ]
  },
  {
   "title": "节点数据磁盘每秒读写次数",
   "type": "graph",
   "description": "节点数据磁盘每秒读写次数-云数据库 GaussDB：该指标用于统计测量对象的节点数据磁盘每秒读写次数，该值为实时值",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "次/秒" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds014_iops{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据磁盘每秒读写次数）"
    }
   ]
  },
  {
   "title": "节点数据磁盘写吞吐量",
   "type": "graph",
   "description": "节点数据磁盘写吞吐量-云数据库 GaussDB：该指标用于统计测量对象的节点数据磁盘每秒写吞吐量，该值为实时值",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds016_disk_write_throughput{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据磁盘写吞吐量）"
    }
   ]
  },
  {
   "title": "节点数据磁盘读吞吐量",
   "type": "graph",
   "description": "节点数据磁盘读吞吐量-云数据库 GaussDB：该指标用于统计测量对象的节点数据磁盘每秒读吞吐量，该值为实时值",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds017_disk_read_throughput{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据磁盘读吞吐量）"
    }
   ]
  },
  {
   "title": "节点数据磁盘单次写入花费的时间",
   "type": "graph",
   "description": "节点数据磁盘单次写入花费的时间-云数据库 GaussDB：该指标用于统计测量对象的节点数据磁盘单次写入花费的时间，取时间段的平均值",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds020_avg_disk_ms_per_write{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据磁盘单次写入花费的时间）"
    }
   ]
  },
  {
   "title": "节点数据磁盘单次读取花费的时间",
   "type": "graph",
   "description": "节点数据磁盘单次读取花费的时间-云数据库 GaussDB：该指标用于统计测量对象的节点数据磁盘单次读取花费的时间，取时间段的平均值",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_gaussdbv5_rds021_avg_disk_ms_per_read{name=~\"$InstanceName\"}",
     "legendFormat": "实例名：{{name}}；节点名：{{nodeName}}（节点数据磁盘单次读取花费的时间）"
    }
   ]
  }
 ]
}