{
 "title": "GeminiDB For Redis",
 "description": "【华为云GeminiDB For Redis支持的监控指标】https://support.huaweicloud.com/redisug-nosql/nosql_10_0036.html#nosql_10_0036__table764033061510",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  { "title": "GeminiDB For Redis 实例指标监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GeminiDB For Redis实例指标概览【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis667_cluster_qps{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_redis668_cluster_key_counts{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_redis803_cluster_all_avg_usec{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_redis807_cluster_all_connection_count{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_redis688_qps_send_total{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_redis689_qps_receive_total{epId=~\"$EPS\", type=~\"redis\"}"
    }
   ]
  },
  {
   "title": "实例的QPS",
   "type": "graph",
   "description": "该指标为实例的QPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis667_cluster_qps{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例的Key数量",
   "type": "graph",
   "description": "该指标为实例的key总数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis668_cluster_key_counts{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例的平均时延",
   "type": "graph",
   "description": "该指标为实例的平均时延。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis803_cluster_all_avg_usec{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例的总连接数",
   "type": "graph",
   "description": "该指标为实例的总连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis807_cluster_all_connection_count{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例的连接数使用率",
   "type": "graph",
   "description": "该指标为实例中最大的节点连接数使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis806_cluster_max_connection_usage{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例的每秒新建连接数",
   "type": "graph",
   "description": "该指标为实例的每秒新建连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis808_cluster_new_client_connection{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例级发送总流量",
   "type": "graph",
   "description": "描述该实例所发送的总流量，反映应用侧流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis688_qps_send_total{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  {
   "title": "实例级接收总流量",
   "type": "graph",
   "description": "描述该实例所接收的总流量，反映应用侧流量大小。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis689_qps_receive_total{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；负载均衡IP：{{lbIPAddress}}"
    }
   ]
  },
  { "title": "GeminiDB For Redis 节点指标监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "GeminiDB For Redis 节点指标概览【企业项目：$EPS】",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql001_cpu_usage{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_nosql002_mem_usage{epId=~\"$EPS\", type=~\"redis\"}"
    },
    {
     "expr": "huaweicloud_sys_nosql_nosql005_disk_usage{epId=~\"$EPS\", type=~\"redis\"}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "该指标为从系统层面采集的CPU使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql001_cpu_usage{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "该指标为从系统层面采集的内存使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql002_mem_usage{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "存储容量使用率",
   "type": "graph",
   "description": "该指标为存储容量使用率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_nosql005_disk_usage{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "graph",
   "description": "采集周期（1分钟）内的连接数使用率，计算方法为：已使用连接数÷总连接数。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis669_connection_usage{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "访问平均时延",
   "type": "graph",
   "description": "该指标为节点执行所有命令的平均时延。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis316_all_avg_usec{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "访问最大时延",
   "type": "graph",
   "description": "该指标为节点执行所有命令的最大时延。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis317_all_max_usec{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "节点发送流量速率",
   "type": "graph",
   "description": "该指标为节点发送客服端的流量速率。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis021_proxy_send_client_bps{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "节点接收流量速率",
   "type": "graph",
   "description": "该指标为节点接收客服端的流量速率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis020_proxy_recv_client_bps{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "graph",
   "description": "采集周期内的命中率, 计算方法为: Key命中数÷(Key命中数+Key未命中数)。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_nosql_redis670_hit_rate{epId=~\"$EPS\", type=~\"redis\"}",
     "legendFormat": "实例名称：{{instanceName}}；实例类型：{{mode}}；节点名称：{{nodeName}}"
    }
   ]
  }
 ]
}