{
 "title": "主机安全服务（HSS）",
 "description": "【华为云HSS支持的监控指标】https://support.huaweicloud.com/usermanual-hss2.0/hss_01_0527.html",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "服务器总数",
   "type": "timeseries",
   "description": "该指标用于统计服务器总数。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_hss_host_num{epId=~\"$EPS\"}",
     "legendFormat": "企业项目名称：{{epName}}"
    }
   ]
  },
  {
   "title": "有风险服务器数量",
   "type": "timeseries",
   "description": "该指标用于统计经检测判定存在风险的服务器的数量。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_hss_risky_host_num{epId=~\"$EPS\"}",
     "legendFormat": "企业项目名称：{{epName}}"
    }
   ]
  },
  {
   "title": "未开启防护服务器数量",
   "type": "timeseries",
   "description": "该指标用于统计未开启防护的服务器数量。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_hss_unprotected_host_num{epId=~\"$EPS\"}",
     "legendFormat": "企业项目名称：{{epName}}"
    }
   ]
  },
  {
   "title": "未安装/已离线agent数量",
   "type": "timeseries",
   "description": "该指标用于统计未安装agent或者状态为离线的agent的数量。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "huaweicloud_sys_hss_uninstalled_or_offline_agent_num{epId=~\"$EPS\"}",
     "legendFormat": "企业项目名称：{{epName}}"
    }
   ]
  }
 ]
}