{
 "title": "视频直播（LIVE）",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "5xx状态码占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_live_http_5xx_proportion",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "拉流并发数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "huaweicloud_sys_live_online", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "4xx状态码占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_live_http_4xx_proportion",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "拉流带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "huaweicloud_sys_live_bandwidth", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "每秒访问次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "huaweicloud_sys_live_qps", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "推流并发数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_live_inject_concurrency_number",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "播放流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_live_play_traffic",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "推流带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_live_inject_bandwidth",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}