{
 "title": "云日志服务（LTS）",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "日志分组指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "写入行数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_written_rows{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "写入流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_write_traffic{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "存储量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_used_storage{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "索引流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_indexing_traffic{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "读取次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_number_of_reads{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "读取流量（字节）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_read_traffic{log_stream_id=\"\"}",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  { "title": "日志流指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "写入行数（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_written_rows{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  },
  {
   "title": "写入流量（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_write_traffic{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  },
  {
   "title": "存储量（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_used_storage{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  },
  {
   "title": "索引流量（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_indexing_traffic{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  },
  {
   "title": "读取次数（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_number_of_reads{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  },
  {
   "title": "读取流量（日志流）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_lts_read_traffic{log_stream_id!=\"\"}",
     "legendFormat": "{{log_group_name}}>{{log_stream_name}}"
    }
   ]
  }
 ]
}