{
 "title": "对象存储服务 OBS",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "桶名称",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET类请求TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_get_per_second{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    },
    {
     "title": "PUT类请求TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_put_per_second{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    },
    {
     "title": "请求成功率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_success_rate{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    },
    {
     "title": "2xx状态码个数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_monitor_2XX{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    },
    {
     "title": "总上传带宽",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_upload_bytes{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    },
    {
     "title": "总下载带宽",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_download_bytes{tenant_id=\"\",api_name=\"\",domain_name=\"\",http_code=\"\"}",
       "legendFormat": "{{bucket_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "用户",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET类请求TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_get_per_second{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    },
    {
     "title": "PUT类请求TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_put_per_second{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    },
    {
     "title": "请求成功率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_success_rate{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    },
    {
     "title": "2xx状态码个数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_request_count_monitor_2XX{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    },
    {
     "title": "总上传带宽",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_upload_bytes{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    },
    {
     "title": "总下载带宽",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "huaweicloud_sys_obs_download_bytes{bucket_name=\"\",http_code=\"\"}",
       "legendFormat": "{{tenant_id}}"
      }
     ]
    }
   ]
  }
 ]
}