{
 "title": "Web应用防火墙(WAF)-独享实例引擎监控看板",
 "description": "【华为云WAF监控指标说明】https://support.huaweicloud.com/usermanual-waf/waf_01_0372.html",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_name",
    "label": "独享引擎实例名称",
    "query": {
     "query": "label_values(huaweicloud_sys_waf_cpu_util,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_cpu_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_mem_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-内存使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_disk_util{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-磁盘使用率"
    }
   ]
  },
  {
   "title": "活跃连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_active_connections{unit=\"Count\",name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-活跃连接数"
    }
   ]
  },
  {
   "title": "网络流入速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_network_incoming_bytes_rate{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-网络流入速率"
    }
   ]
  },
  {
   "title": "网络流出速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_network_outgoing_bytes_rate{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-网络流出速率"
    }
   ]
  },
  {
   "title": "并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_concurrent_connections{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-并发连接数"
    }
   ]
  },
  {
   "title": "最近一次策略同步的耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_latest_policy_sync_time{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-最近一次策略同步的耗时"
    }
   ]
  },
  {
   "title": "磁盘可用空间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_waf_disk_avail_size{name=~\"$instance_name\"}",
     "legendFormat": "{{name}}-磁盘可用空间"
    }
   ]
  }
 ]
}