{
 "title": "广域网质量监控",
 "description": "CES服务广域网质量监控看板",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operator",
    "label": "运营商",
    "query": "中国移动 : \"CMCC\",中国联通 : \"CUCC\",中国电信 : \"CTCC\""
   },
   {
    "name": "city",
    "label": "探测点城市",
    "query": "南宁 : \"Nanning\",青岛 : \"Qingdao\",无锡 : \"Wuxi\",哈尔滨 : \"Harbin\",东莞 : \"Dongguan\",南昌 : \"Nanchang\",拉萨 : \"Lhasa\",杭州 : \"Hangzhou\",石家庄 : \"Shijiazhuang\",银川 : \"Yinchuan\",天津 : \"Tianjin\",太原 : \"Taiyuan\",武汉 : \"Wuhan\",重庆 : \"Chongqing\",济南 : \"Jinan\",广州 : \"Guangzhou\",苏州 : \"Suzhou\",中卫 : \"Zhongwei\",郑州 : \"Zhengzhou\",贵阳 : \"Guiyang\",福州 : \"Fuzhou\",深圳 : \"Shenzhen\",南京 : \"Nanjing\",西宁 : \"Xining\",昆明 : \"Kunming\",乌鲁木齐 : \"Urumqi\",上海 : \"Shanghai\",呼和浩特 : \"Hohhot\",合肥 : \"Hefei\",扬州 : \"Yangzhou\",兰州 : \"Lanzhou\",长沙 : \"Changsha\",佛山 : \"Foshan\",宁波 : \"Ningbo\",成都 : \"Chengdu\",沈阳 : \"Shenyang\",厦门 : \"Xiamen\""
   }
  ]
 },
 "panels": [
  {
   "title": "平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_rtt_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "重定向时间平均值（HTTP类型任务）",
   "type": "timeseries",
   "description": "HTTP类型指标",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_redirect_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "DNS域名解析时间平均值",
   "type": "timeseries",
   "description": "HTTP类型指标",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_dns_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "连接时间平均值（HTTP类型任务）",
   "type": "timeseries",
   "description": "HTTP类型任务指标",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_connection_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "HTTP请求时间平均值（HTTP类型任务）",
   "type": "timeseries",
   "description": "HTTP类型任务专有指标",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_request_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "HTTP请求时间平均值（HTTP任务）",
   "type": "timeseries",
   "description": "HTTP类型任务指标专有指标",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_request_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "下载时间平均值（HTTP类型任务）",
   "type": "timeseries",
   "description": "HTTP类型任务指标",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_download_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "重定向时间平均值（HTTP类型任务）",
   "type": "timeseries",
   "description": "HTTP类型任务指标",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_redirect_cost_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  },
  {
   "title": "平均丢包率（仅DNS和ping类型任务可用）",
   "type": "timeseries",
   "description": "仅DNS和ping类型任务可用",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_wanqmonitor_packet_loss_rate_avg{operator=$operator,city=$city}",
     "legendFormat": "{{taskName}}-{{protocol}}"
    }
   ]
  }
 ]
}